# Generated by Django 3.0.4 on 2020-03-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
    ]
