# Generated by Django 3.0.4 on 2020-03-04 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_backend', '0002_auto_20200304_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
